// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPHzMgKA0ae5dHyZzJBI6_K1_uS_Eacs',
    appId: '1:492323940704:web:2c91ab43d4d65df40e5605',
    messagingSenderId: '492323940704',
    projectId: 'eyego-task-324d7',
    authDomain: 'eyego-task-324d7.firebaseapp.com',
    storageBucket: 'eyego-task-324d7.firebasestorage.app',
    measurementId: 'G-FLEM280XH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGtPQo6CPhMbfNxAY8COXDxmnVxAhScg',
    appId: '1:492323940704:android:b169908dc89511b20e5605',
    messagingSenderId: '492323940704',
    projectId: 'eyego-task-324d7',
    storageBucket: 'eyego-task-324d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsk3MJMBWS_bmbq1DIBGpZ8hTYmomEH3c',
    appId: '1:492323940704:ios:9a17c0af38147dfc0e5605',
    messagingSenderId: '492323940704',
    projectId: 'eyego-task-324d7',
    storageBucket: 'eyego-task-324d7.firebasestorage.app',
    iosBundleId: 'com.example.eyegoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsk3MJMBWS_bmbq1DIBGpZ8hTYmomEH3c',
    appId: '1:492323940704:ios:9a17c0af38147dfc0e5605',
    messagingSenderId: '492323940704',
    projectId: 'eyego-task-324d7',
    storageBucket: 'eyego-task-324d7.firebasestorage.app',
    iosBundleId: 'com.example.eyegoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUPHzMgKA0ae5dHyZzJBI6_K1_uS_Eacs',
    appId: '1:492323940704:web:acf33240acfa170f0e5605',
    messagingSenderId: '492323940704',
    projectId: 'eyego-task-324d7',
    authDomain: 'eyego-task-324d7.firebaseapp.com',
    storageBucket: 'eyego-task-324d7.firebasestorage.app',
    measurementId: 'G-S1HF1BKWCM',
  );
}
